"""Generate static/css/skins.css from SAMSEL_V3_PRO._SKIN_REPLACEMENTS."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
text = (ROOT.parent / "SAMSEL_V3_PRO.py").read_text(encoding="utf-8")
m = re.search(
    r"_SKIN_REPLACEMENTS:\s*Dict\[str, List\[Tuple\[str, str\]\]\]\s*=\s*(\{.*?\n\})",
    text,
    re.DOTALL,
)
if not m:
    raise SystemExit("Could not find _SKIN_REPLACEMENTS")
_SKIN_REPLACEMENTS = eval(m.group(1))


def norm(h: str) -> str:
    h = h.strip().lower().lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    return "#" + h


def apply_skin(mid: str, skin: str) -> str:
    mid = norm(mid)
    for old, new in _SKIN_REPLACEMENTS.get(skin, []):
        if norm(old) == mid:
            return norm(new)
    return mid


ALIASES = {
    "#8ab4ff": "#a8b4ff",
}

VARS = {
    "bg0": "#070714",
    "bg1": "#12122a",
    "grad1": "#12082a",
    "grad2": "#0a1430",
    "bg2": "#181830",
    "accent": "#667eea",
    "accent2": "#7b68ee",
    "text": "#eaeaea",
    "muted": "#8899cc",
    "danger": "#ff6b6d",
    "white": "#ffffff",
    "tab-br": "#3d4a32",
    "tab-bg1": "#4a5c38",
    "tab-bg2": "#2a2218",
    "tab-fg": "#f4f1e6",
    "tab-act1": "#3d4a2e",
    "tab-act2": "#1a1f12",
    "tab-act-fg": "#fffef4",
    "card-br": "#5566aa",
    "btn-g1": "#6a8cff",
    "btn-g2": "#7b4fd6",
    "btn-g3": "#c94b9e",
    "btn-out": "#aabbff",
    "playlist-br": "#3a3a6a",
    "playlist-g1": "#181840",
    "playlist-g2": "#0a0a28",
    "pl-row-br": "#2a2a44",
    "pl-hover": "#2f2f55",
    "pl-active": "#4a4a8e",
    "lrc-tag": "#8ab4ff",
    "eq-bg": "#0e0e22",
    "eq-accent": "#66eeff",
    "eq-db": "#d0d8ff",
    "meta": "#e4e4e4",
    "status-ok": "#7bed9f",
    "inp-br": "#4455aa",
    "inp-bg": "#14142c",
    "sel-br": "#7788dd",
    "sel-bg": "#1a1a38",
    "stat-txt": "#cce0ff",
    "ly-bg": "#0a0a28",
    "ly-muted": "#aaaaaa",
    "ly-cur": "#ffffff",
    "h2": "#cce0ff",
    "spin-shadow": "#667eea",
}


def map_hex(h: str, skin: str) -> str:
    h = norm(h)
    if h in ALIASES:
        h = ALIASES[h]
    return apply_skin(h, skin)


def main() -> None:
    out: list[str] = []
    out.append(
        "/* Generated by tools/gen_skins_css.py from SAMSEL_V3_PRO skin replacement tables. */"
    )
    out.append(":root,")
    out.append('[data-skin="midnight"] {')
    for k, v in VARS.items():
        out.append(f"  --skin-{k}: {norm(v)};")
    out.append("  --skin-accent-rgb: 102, 126, 234;")
    out.append("}")

    for skin in ("camo", "carbon", "sunset"):
        out.append(f'[data-skin="{skin}"] {{')
        for k, v in VARS.items():
            out.append(f"  --skin-{k}: {map_hex(v, skin)};")
        ac = map_hex(VARS["accent"], skin).lstrip("#")
        r, g, b = int(ac[0:2], 16), int(ac[2:4], 16), int(ac[4:6], 16)
        out.append(f"  --skin-accent-rgb: {r}, {g}, {b};")
        out.append("}")

    out_path = ROOT / "static" / "css" / "skins.css"
    out_path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("Wrote", out_path)


if __name__ == "__main__":
    main()
